site_name: UI自动化教程
site_description: UI自动化最佳方案
site_author: teark

# 导航结构
nav:
  - 首页: index.md
  - UI自动化:
    - 环境准备: 1.环境准备.md
    - 如何写出高稳定性的xpath？: 2.如何写出高稳定性的xpath？.md
    - pytest会这几个足够了: 3.pytest会这几个足够了.md
    - ui自动化四层结构思想: 4.ui自动化四层结构思想.md
    - 逐渐深入的3个demo: 5.逐渐深入的3个demo.md
  - 效果展示: 6.效果展示.md
  - 关于: about.md

# 主题设置
theme:
#  name: mkdocs  # 使用 Material 主题
  name: material  # 使用 Material 主题
  language: zh  # 中文界面
#  locale: zh  # 默认语言
  palette:
    primary: indigo  # 主色调
    accent: pink     # 强调色

# 额外功能
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 中文
          build: true
      nav_translations:
        en:
          Home: Home
          Tutorial: Tutorial
        zh:
          Home: 首页
          Tutorial: 教程
